#!/bin/sh

# Rips a dvd (or a iso file extracted from a dvd) to an avi file
# params
# $1 iso file (dvd-device)
# $2 dvd track (usually 1)
# $3 desired video bitrate
# $4 output avi file


if [ $# -lt 4 ]; then
	echo "Es necesario introducir al menos 4 parámetros: $0 dvd-device dvd-track bitrate outuput"
	exit 1
fi

# remove conflicting files
rm -f divx2pass.log frameno.avi

#pass 1
mencoder dvd://$2 -dvd-device "$1" -alang es -ovc xvid -xvidencopts bvhq=1:chroma_opt:quant_type=mpeg:bitrate=$3:pass=1 -oac copy -o /dev/null

#pass 2, compress audio 128
mencoder dvd://$2 -dvd-device "$1" -ovc xvid -xvidencopts bvhq=1:chroma_opt:quant_type=mpeg:bitrate=$3:pass=2 -alang es -oac mp3lame -lameopts br=128:cbr:vol=6 -o $4
