#!/bin/bash

FECHA=$(date)
FECHA_=$(date +%F)
FICHERO_LOG=~/.tostado.log
LIMITE=365475
DEV=""
CDRECORD_OPTS="driveropts=burnfree -overburn -dao -v -eject gracetime=2 -immed"
MKISOFS_OPTS=" -r -J -jcharset default -l -D -L -joliet-long "
DIRECTORIO=$1
if [ -z "$1" ]; then
	echo "Uso: $0 directorio_a_tostar"
	exit
fi
if [ ! -d "$1" ]; then
	echo El directorio especificado $1  no existe
fi


VOL_ID=`echo "${DIRECTORIO}" | cut -b -32 -`

TAMANO=`mkisofs ${MKISOFS_OPTS} --print-size  -V "${VOL_ID}" -graft-points "/=/$(pwd)/${DIRECTORIO}"`
if [ $TAMANO -gt $LIMITE ]; then
	echo "Demasiado grande para caber en un cd: $TAMANO, maximo $LIMITE"
	exit
fi
`mkisofs ${MKISOFS_OPTS} -V "${VOL_ID}" -graft-points "/=/$(pwd)/${DIRECTORIO}" 2>/dev/null | cdrecord $DEV $CDRECORD_OPTS tsize=${TAMANO}s - 1>&2`
RETVAL=$?
[ $RETVAL -eq 0 ] && echo "$FECHA - $1" >> $FICHERO_LOG
