#!/bin/bash

DEVICE=0,3,0
BUFFERS=300
FICHERO_LOG=~/.tostado.log
FECHA=$(date)
if [ -z "$1" ]; then
	echo "Uso: $0 cue_a_tostar"
	exit
fi
if [ ! -f "$1" ]; then
	echo "El archivo especificado \"$1\" no existe"
	exit
fi
cdrdao write --device $DEVICE --driver generic-mmc -n -v 2 --buffers $BUFFERS "$1"
RETVAL=$?
[ $RETVAL -eq 0 ] && echo "$FECHA - $1" >> $FICHERO_LOG
	
